### ISSUE TITLE
Logo For Chat App

### ISSUE THREAD

**Issue by zularizal** [felipehjcosta/chat-app#1]
Hi @felipehjcosta , I'm a graphic designer, you have a good project but you don't have a logo yet. Therefore, I want to contribute by creating a free logo for your project. What do you think?

**Comment by felipehjcosta** [comment]
Hi @zularizal that will be great! What do you have in mind? Thanks!

**Comment by zularizal** [comment]
Okay, I need time to make it. Before that, I have a few questions, what is the name of this app and can you explain a little about the description of this app. I need an idea to include it in the logo.

**Comment by zularizal** [comment]
Hi, I'm sorry, I can't continue.
